### ISSUE TITLE
decoding str is not supported

### ISSUE THREAD

**Issue by MarioMasta64** [andymcca/sshflash-win#8]
appears to error out on windows 11 (specifically every problem seems to be "decoding str is not supported"):

```
Lines to write (should be a whole number) -
344
Traceback (most recent call last):
  File "mount.py", line 136, in find_device_id
    lines = str(self.sg_scan(), 'utf-8').split('\n')
TypeError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mount.py", line 232, in get_device_id_i
    return self._device_id or self.find_device_id()
  File "mount.py", line 174, in find_device_id
    self.error(e)
  File "mount.py", line 86, in error
    assert False, '%s' % e
AssertionError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "interface.py", line 51, in get_device_id
    return self._connection.get_device_id_i()
  File "mount.py", line 234, in get_device_id_i
    self.error(e)
  File "mount.py", line 86, in error
    assert False, '%s' % e
AssertionError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pager.py", line 105, in upload
    cmdl = '%s %s -b -s %s -n 2A 00 00 00 00 %s 00 00 20 00' % (self._sg_raw, self._mount_config.device_id, cbf.PACKET_SIZE, byte1)
  File "interface.py", line 53, in get_device_id
    self._connection.rerror(e)
  File "mount.py", line 89, in rerror
    assert False, 'Mount Error: %s' % e
AssertionError: Mount Error: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "boot_surgeon.py", line 25, in <module>
  File "boot_surgeon.py", line 16, in do_surgeon_boot
  File "pager.py", line 124, in upload
    self.rerror(e)
  File "pager.py", line 66, in rerror
    assert False, 'Pager Error: %s' % e
AssertionError: Pager Error: Mount Error: decoding str is not supported
[5200] Failed to execute script 'boot_surgeon' due to unhandled exception!
Done! Waiting for Surgeon to come up...
```

**Comment by andymcca** [comment]
I'll try and check it out (haven't got a Windows 11 machine to hand just at the moment), but please make sure you have all the files present that are in the zip file, as Windows Defender in particular detects a false AV positive on boot_surgeon. exe.  Also, make sure you have the Datalogic USB driver in place and have assigned the correct IP.

**Comment by andymcca** [comment]
OK - have done a few flashes in recent days and have seen this in certain scenarios.  Please ensure that -

- you are in an Administrator-level command prompt when running sshflash-win
- you have the Datalogic driver loaded/applied against the USB connection, and IP is set as 169.254.8.x (anything but 1)
- Windows Defender (or another AV shield) isn't blocking boot_surgeon.exe.  Windows Defender in particular seems to take a shine to this file and will try and block it at every opportunity, sadly!  Even after allowing it in Windows Defender, please also double click on it to run it, to make sure Defender isn't blocking it.
- After confirming all of the above, try flashing again from a new Admin Command Prompt instance

**Comment by Time0s** [comment]
Hey so what is happening on this issue is that the device is not being detected. I modified the code locally to get around the error which are with lines 125 and 127 in mount.py these need to be b'' and not '' so the encoding won't throw this error. I'm investigating more into this to see why this does not detect the Device currently using an Explorer.

Edit: Looks like the sg_scan is not detecting the device atleast not by its vendor name. Its only detecting my HDD in my Windows 10 machine. Its not detecting the USB ports. I've tried using sshflash v0.3 and v0.2 that lead to the same results.

**Comment by IdonotknowwhatIamdoin** [comment]
"> * you have the Datalogic driver loaded/applied against the USB connection, and IP is set as 169.254.8.x (anything but 1)"
how do I load/apply the driver?

**Comment by timmit99** [comment]
Following this as well. 
Windows 10 `10.0.19045 Build 19045`
using the following files:
sshflash-win.v0.3.alpha
retroleap_v2.0.0-alpha10


Both extracted to the same folder location:
![image](https://github.com/andymcca/sshflash-win/assets/8399317/479f8aff-faf4-47f3-90a9-0e8f74f995b4)

Running command prompt as administrator, running `sshflash-win.bat`, putting the Leapster GS into flashing mode, and selecting the right options.
Errors out after writing the CBF file:
![image](https://github.com/andymcca/sshflash-win/assets/8399317/90d8ebbe-df35-4b9f-996e-e1fc8cd2225a)

Tried a few different versions of the softwares and disabled windows defender with no avail. Please Help!

**Comment by timmit99** [comment]
@

> "> * you have the Datalogic driver loaded/applied against the USB connection, and IP is set as 169.254.8.x (anything but 1)" how do I load/apply the driver?

Did you ever figure this out?
